name: Format Check

on: [pull_request]

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install jq
      run: sudo apt-get install -y jq
    
    - name: Check JSON format
      run: |
        FILES=$(git diff --name-only --diff-filter=d origin/main...HEAD | grep '\.json$' || true)
        if [ -n "$FILES" ]; then
          for FILE in $FILES; do
            if ! jq . $FILE > /dev/null 2>&1; then
              echo "JSON file $FILE is not formatted correctly"
              exit 1
            fi
          done
        else
          echo "No JSON files to check."
        fi
