name: JSON Validation

on:
  pull_request:
    branches:
      - main

jobs:
  json-validation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install jq
      run: sudo apt-get install -y jq
    
    - name: List changed files
      run: git diff --name-only --diff-filter=d origin/main...HEAD
    
    - name: Validate JSON files
      run: |
        FILES=$(git diff --name-only --diff-filter=d origin/main...HEAD | grep '\.json$' || true)
        echo "JSON files to validate: $FILES"
        if [ -n "$FILES" ]; then
          for FILE in $FILES; do
            echo "Validating $FILE"
            # Check if the file is a valid JSON
            if ! jq empty $FILE > /dev/null 2>&1; then
              echo "Error: $FILE is not a valid JSON file"
              exit 1
            fi
            # Check for duplicate keys
            if jq 'walk(if type == "object" then with_entries(select(.key as $k | .key | index($k) | length > 1)) else . end)' $FILE | grep . > /dev/null 2>&1; then
              echo "Error: $FILE contains duplicate keys"
              exit 1
            fi
          done
        else
          echo "No JSON files to validate."
        fi
