name: JSON Syntax Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  json-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jsonlint
        run: npm install -g jsonlint

      - name: Find and validate JSON files
        run: |
          # Search for JSON files and validate syntax
          find . -name "*.json" -print0 | xargs -0 jsonlint -q